AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  twitter-unpack

  Sample SAM Template for twitter-unpack

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  S3toDynamoDBFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/
      Handler: app.handler
      Runtime: nodejs12.x
      Events:
        S3toDynamoDB:
          Type: S3
          Properties:
            Bucket: my-test-bucket # bucket must be created in the same template
            Events: s3:ObjectCreated:*


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api

  S3toDynamoDBFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt S3toDynamoDBFunction.Arn
  S3toDynamoDBFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt S3toDynamoDBFunctionRole.Arn
